### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ItsSitanshu**

### CODE REVIEW

**Comment by ItsSitanshu** [comment]
Its late and sorry again @giacomo-b

**Comment by giacomo-b** [comment]
No worries at all, thank you for taking the time to go through it! Just submit a new PR whenever you are done

**Comment by ItsSitanshu** [comment]
Thanks for being cool about it! I might add some algorithms to the actual code today.

**Comment by giacomo-b** [comment]
Awesome! Since I still have to create the CONTRIBUTE document, let me just specify a few quick points before you submit PRs:

- Make sure you run clang-format before committing, otherwise the style test will fail
- The library (at least at this point) is header-only and uses templates that take the problem dimensions
- The EKF interface is similar to what I would like to have, the LQR API unfortunately is very poor and I need to fix it.

**Pull request merged**
